name: Terraform Resuable Workflow
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      action:
        required: true
        type: string
    secrets:
      aws_role_arn:
        required: true
      aws_region:
        required: true
          
      
