name: Terraform Resuable Workflow
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      action:
        required: true
        type: string
    secrets:
      aws_role_arn:
        required: true
      aws_region:
        required: true
  
jobs:
  terraform:
    runs-on: ubuntu-latest
      permissions:
        id-token: write      # <- This is required for OIDC
        contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: List Files for Debugging
        run: ls -la
        # This will help you confirm that the directory structure is as expected

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::255945442255:role/sankari-github-oidc-deploy-role
          aws-region: ap-southeast-1
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7' # or latest stable


      
